server:
  port: 8082
spring:
  profiles:
    active: $activatedProperties$
  servlet:
    multipart:
      max-file-size: 5MB
  config:
    import: optional:file:.env[.properties]

  # i188n config
  messages:
    # Whether to always apply the MessageFormat rules, parsing even messages without arguments.
    always-use-message-format: false
    # Comma-separated list of basenames
    basename: i18n/messages
    # Loaded resource bundle files cache duration.
    # When not set, bundles are cached forever.
    # If a duration suffix is not specified, seconds will be used.
    #    cache-duration: 10
    # Message bundles encoding.
    encoding: UTF-8
    # Whether to fall back to the system Locale
    # if no files for a specific Locale have been found.
    fallback-to-system-locale: false
    # Whether to use the message code as the default message instead of throwing a "NoSuchMessageException".
    # Recommended during development only.
    use-code-as-default-message: false

jwt:
  secret: jaklsdj1283e7osalkd
  expiration: 36000 #10 * 60 * 60 (10 hours)
  longExpiration: 604800 #7 * 24 * 60 * 60 (7 days)

logging:
  file:
    path: ./logs
    name: ./logs/application.log
  logback:
    rollingpolicy:
      file-name-pattern: ./logs/application.log.%d{yyyy-MM-dd}.%i.log # by date
      max-file-size: 1MB # by size
      max-history: 30 # maximum number of days that archive log files
      clean-history-on-start: true
      total-size-cap: 50MB # maximum number of all log file size


  level:
    ROOT: INFO
    org.springframework.orm.jpa: INFO
    org.springframework.transaction: INFO
    org.hibernate.engine.transaction.internal.TransactionImpl: INFO
    org.hibernate.engine.jdbc.batch.internal: ERROR

minio:
  buckek:
    name:
  access:
    name: ${MINIO_ROOT_USER}
    secret: ${MINIO_ROOT_PASSWORD}
  url:
  endpoint: ${HTTPS_DOMAIN}

app:
  firebase-configuration-file:
