version: "2"

services:
  vietdangapp:
    env_file:
      - .env
    container_name: vietdangapp
    build: .
    ports:
      - "8080:8080"
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - vietdang_network
    volumes:
      - ./logs:/logs

networks:
  vietdang_network:
    external: true
    name: vietdang_network