version: "2"

services:
  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    ports:
      - "80:80"
      - "443:443"
    restart: always
    networks:
      - vietdang_network

networks:
  vietdang_network:
    external: true
    name: vietdang_network