spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://127.0.0.1:4200,http://127.0.0.1:3001,http://localhost:4200"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTIONS
      routes:
        - id: authentication-service
          uri: lb://AUTHENTICATION-SERVICE
          predicates:
            - Path=/api/accounts/**, /api/auth/**, /api/roles/**
        - id: job-service
          uri: lb://job-service
          predicates:
            - Path=/api/jobs/**
        - id: tracking-service
          uri: lb://tracking-service
          predicates:
            - Path=/api/applications/**
        - id: configuration-service
          uri: lb://configuration-service
          predicates:
            - Path=/api/configuration/**
        - id: email-service
          uri: lb://email-service
          predicates:
            - Path=/api/email/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
